import "../../../globals.css";
export const metadata = {
  title: "Dashboard-UserProfile",
  description: "Generated by Next.js",
};

function UserProfile() {
  const data = {
    name: "John do",
    email: "john@example.com",
    image:
      "https://img.freepik.com/free-vector/delivery-scooter-with-flat-design_23-2147677471.jpg?",
  };
  return (
    <div>
      <div className=" bg-white h-screen  w-full p-4">
        <div className="  mt-8 w-full">
          <div className="w-full max-w-sm bg-orange-200 border border-gray-200 rounded-lg shadow-[-10px_-10px_30px_4px_rgba(0,0,0,0.1),_10px_10px_30px_4px_rgba(45,78,255,0.15)]">
            <div className=" flex-col items-center pb-10">
              <div
                className="w-full  "
                style={{
                  backgroundImage:
                    "url(https://img.freepik.com/free-photo/fresh-pasta-with-hearty-bolognese-parmesan-cheese-generated-by-ai_188544-9469.jpg?)",
                }}
              >
                <img
                  className="w-24 h-24 mb-3 rounded-full shadow-lg ring-2 relative top-14 -right-[140px] "
                  src={data?.image}
                  alt="User image"
                />
              </div>

              <div className=" p-5 text-center mt-10">
                <h5 className="mb-1 text-base bg-red-400 rounded-full font-medium text-gray-900"></h5>
                <h5 className="mb-1 text-base bg-red-400 rounded-full font-medium text-gray-900"></h5>
                <h5 className="mb-1 text-2xl font-medium text-gray-900">
                  email
                </h5>
                <h5 className="mb-1 text-xl font-medium text-gray-900">
                  {data.email}
                </h5>
                <span className="text-sm text-gray-500">
                  Last log in :{/*  {dateOnly} */}
                </span>
              </div>
              {/*  <!-- Action base sized with lead icon buttons  --> */}
              <div className="flex justify-end gap-2 p-6 pt-0 mt-6  ">
                <button className="btn  btn-outline outline-red-700 text-orange-500">
                  Update
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>

    
    </div>
  );
}

export default UserProfile;
