import { Poppins } from "next/font/google";
import "../globals.css";
import Link from "next/link";
export const metadata = {
  title: "Dashboard",
  description: "Generated by Next.js",
};
const poppins = Poppins({
  subsets: ["latin"], // Specify subsets
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins", // Custom variable name
  display: "swap", // Font display strategy
});

export default function RootLayout({ children }) {
  const role = "deleveryMan";
  const customerLinks = (
    <>
      <li>
        <Link href="/" className="text-[#533831] hover:text-[#333] transition duration-200">
          Home
        </Link>
      </li>
      <li>
        <Link
          href="/dashboard/userProfile"
          className="text-[#533831] hover:text-[#333] transition duration-200"
        >
          Profile
        </Link>
      </li>
      <li>
        <Link href="" className="text-[#533831] hover:text-[#333] transition duration-200">
          Recent Order
        </Link>
      </li>
      <li>
        <Link href="" className="text-[#533831] hover:text-[#333] transition duration-200">
          Notification
        </Link>
      </li>
    </>
  );
  
  const admins = (
    <>
      <li>
        <Link href="" className="text-[#533831] hover:text-[#333] transition duration-200">
          Admin Overview
        </Link>
      </li>
      <li>
        <Link href="" className="text-[#533831] hover:text-[#333] transition duration-200">
          Product
        </Link>
      </li>
      <li>
        <Link href="" className="text-[#533831] hover:text-[#333] transition duration-200">
          Order
        </Link>
      </li>
      <li>
        <Link href="" className="text-[#533831] hover:text-[#333] transition duration-200">
          Setting
        </Link>
      </li>
    </>
  );
  
  const deleveryMan = (
    <>
      <li>
        <Link href="" className="text-[#533831] hover:text-[#333] transition duration-200">
          Assigned Order
        </Link>
      </li>
      <li>
        <Link href="" className="text-[#533831] hover:text-[#333] transition duration-200">
          Update Assigned
        </Link>
      </li>
      <li>
        <Link href="" className="text-[#533831] hover:text-[#333] transition duration-200">
          Earning
        </Link>
      </li>
    </>
  );
  

  return (
 <html lang="en" data-theme="light" className="bg-[#E5D0BB]">
  <head>
    {/* Head Content */}
  </head>
  <body className={`${poppins.variable} antialiased`}>
    {/* Drawer Structure */}
    <div className="drawer lg:drawer-open">
      {/* Drawer Toggle */}
      <input id="my-drawer-2" type="checkbox" className="drawer-toggle" />
      
      {/* Main Content Area */}
      <div className="drawer-content flex flex-col items-center justify-center">
        {/* Page Content and Children */}
        {children}

        {/* Mobile Toggle Button */}
        <label
          htmlFor="my-drawer-2"
          className="absolute top-4 left-4 bg-[#DFC6AD] text-xl p-2 rounded-full text-[#533831] drawer-button lg:hidden transition ease-in-out duration-300 hover:bg-[#bfa78f]"
        >
          X
        </label>
      </div>
      
      {/* Sidebar */}
      <div className="drawer-side">
        {/* Sidebar Overlay */}
        <label
          htmlFor="my-drawer-2"
          aria-label="close sidebar"
          className="drawer-overlay"
        ></label>

        {/* Sidebar Menu */}
        <ul className="menu bg-[#DFC6AD] min-h-full w-80 p-4 shadow-xl rounded-r-lg">
          {/* Sidebar Links based on Role */}
          {role === "customer"
            ? customerLinks
            : role === "deleveryMan"
            ? deleveryMan
            : admins}
        </ul>
      </div>
    </div>
  </body>
</html>

  );
}
