import { Poppins } from "next/font/google";
import "../globals.css";
import Link from "next/link";

export const metadata = {
  title: "Dashboard",
  description: "Generated by Next.js",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
  display: "swap",
});

export default function RootLayout({ children }) {

  // This can be dynamically set based on user authentication
  const role = "customer";   //role are customer/admin/deleveryMan

  const links = {
    customer: [
      { href: "/", label: "Home" },
      { href: "/dashboard/userProfile", label: "Profile" },
      { href: "", label: "Recent Order" },
      { href: "", label: "Notification" },
    ],
    admin: [
      { href: "", label: "Admin Overview" },
      { href: "", label: "Product" },
      { href: "", label: "Order" },
      { href: "", label: "Setting" },
    ],
    deliveryMan: [
      { href: "", label: "Assigned Order" },
      { href: "", label: "Update Assigned" },
      { href: "", label: "Earning" },
    ]
  };

  return (
    <html lang="en" data-theme="light" className="bg-[#E5D0BB]">
      <head>
        {/* Head Content */}
      </head>
      <body className={`${poppins.variable} antialiased`}>
        <div className="drawer lg:drawer-open">
          <input id="my-drawer-2" type="checkbox" className="drawer-toggle" />
          <div className="drawer-content flex flex-col items-center justify-center">
            {children}
            <label
              htmlFor="my-drawer-2"
              className="absolute top-4 left-4 bg-[#DFC6AD] text-xl p-2 rounded-full text-[#533831] drawer-button lg:hidden transition ease-in-out duration-300 hover:bg-[#bfa78f]"
            >
              X
            </label>
          </div>
          <div className="drawer-side">
            <label
              htmlFor="my-drawer-2"
              aria-label="close sidebar"
              className="drawer-overlay"
            />
            <ul className="menu bg-[#DFC6AD] min-h-full w-80 p-4 shadow-xl rounded-r-lg">
              {links[role]?.map((link) => (
                <li key={link.label}>
                  <Link href={link.href} className="text-[#533831] hover:text-[#333] transition duration-200">
                    {link.label}
                  </Link>
                </li>
              ))}
            </ul>
          </div>
        </div>
      </body>
    </html>
  );
}
