"use Client"
import React from 'react'
import AdminProfile from './(admin)/adminProfile/page';
import DeleveryProfile from './(deleveryMan)/deleveryProfile/page';
import OwnerProfile from './(owner)/ownerProfile/page';
import UserProfile from './(user)/userProfile/page';

export const metadata = {
  title: "Dashboard-UserProfile",
  description: "Generated by Next.js",
};
const DashboardPage = () => {

  const data = {
    name: "John do",
    email: "john@example.com",
    image:"https://thumbs.dreamstime.com/b/delivery-boy-ride-scooter-motorcycle-servic-service-order-worldwide-shipping-fast-free-transport-75096257.jpg",
  };

  const role="user"
  return (
    <div> 
    {
      role === "user"  && <UserProfile></UserProfile>
    }
    
    
    {
      role === "admin" && <AdminProfile />
    }
    
    {
      role === "deleveryMan"  &&  <DeleveryProfile></DeleveryProfile>
    }
    
    
    {
      role === "owner"  &&  <OwnerProfile></OwnerProfile>
    }
    





    
    </div>
  )
}

export default DashboardPage