'use client'
import { SessionProvider } from 'next-auth/react'
import '../globals.css'

 const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <SessionProvider>
      <body>{children}</body>

      </SessionProvider>
    </html>
  )
}